version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5627:5627" # rabbit amqp port
      - "15672:15672" # manage port
    environment:
      - RABBITMQ_DEFAULT_USER=admin # 기본 사용자 이름
      - RABBITMQ_DEFAULT_PASS=1234 # 기본 사용자 비밀번호
